before_script:
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - git clone https://github.com/kannokanno/vmock /tmp/vmock
  - git clone https://github.com/thinca/vim-themis --branch v1.5.1 --single-branch --depth 1 /tmp/vim-themis

script:
  - which -a vim
  - vim --cmd version --cmd quit
  - vim --cmd "try | helptags doc/ | catch | cquit | endtry" --cmd quit
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -e EVL103=1 -e EVL102.l:_=1 -c func_abort=1 autoload plugin macros after
  - /tmp/vim-themis/bin/themis -r --runtimepath /tmp/vmock --reporter dot
