version: '{build}'
clone_depth: 1
environment:
  matrix:
    - VIM_URL: http://files.kaoriya.net/vim/vim74-kaoriya-win64.zip
    # - VIM_URL: http://files.kaoriya.net/vim/2011/vim73-kaoriya-win64-20110306.zip
install:
  - 'cd %APPVEYOR_BUILD_FOLDER%'
  - 'appveyor DownloadFile %VIM_URL% -FileName %TEMP%\vim.zip'
  - '7z x -o%TEMP% %TEMP%\vim.zip > nul'
  - ps: $Env:THEMIS_VIM = (Get-ChildItem $Env:TEMP | Select-Object -First 1).FullName + '\vim.exe'
  # themis
  - 'git -c advice.detachedHead=false clone https://github.com/thinca/vim-themis --quiet --branch v1.5 --single-branch --depth 1 %TEMP%\vim-themis'
  # https://groups.google.com/forum/#!msg/vim_dev/3AkHqiD1NLE/vFw52yh_AAAJ
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:32'
  - 'reg copy HKLM\SOFTWARE\Python\PythonCore\2.7 HKLM\SOFTWARE\Python\PythonCore\2.7-32 /s /reg:64'
build: off
test_script:
  - '%THEMIS_VIM% --version'
  - '%TEMP%\vim-themis\bin\themis.bat -r --reporter dot'
deploy: off
